### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by equant** [intel-isl/Open3D-ML#221] opened 2021-02-11 21:45 UTC
Hi, I've been trying to create a custom dataset and have questions.  On the front README file, there is a link to the How-To "Adding a new dataset" which suggests creating a Class based off of the `BaseDataset`.  However, in the docs I also see the option for using the `Custom3D` class for custom datasets.

I've created a Custom3D dataset for my pointcloud data.  When I pass it into `ml3d.pipelines.SemanticSegmentation()` there are no complaints, and when I pass it into `visualize_dataset()` it works.  

```
model = ml3d.models.RandLANet()

pipeline = ml3d.pipelines.SemanticSegmentation(model=model, dataset=dataset, max_epoch=100)

# prints training progress in the console.
pipeline.run_train()
```

The above code snippet exists with the error "AttributeError: 'SemanticSegmentation' object has no attribute 'cfg_tb'".  

What is the correct way to create a custom dataset?

**Comment by sanskar107** [comment] 2021-02-16 14:59
@equant  could you post full error log here? (line number and file where this error occurs")

**Comment by equant** [comment] 2021-02-17 16:53
Here is the code that I've adapted from the README.md that uses my dataset which inherits from the Custom3D class..

```
import open3d.ml as _ml3d
import open3d.ml.torch as ml3d  # or open3d.ml.tf as ml3d
import supervisely_dataset

dataset_path = '/home/equant/work/sandbox/3D/open3dml/foo_semantic_segmentation/converted_to_o3d_dataset'

dataset = supervisely_dataset.Supervisely(dataset_path=dataset_path, train_dir='train', test_dir='test', val_dir='val')

# get the 'all' split that combines training, validation and test set
all_split = dataset.get_split('all')

# print the attributes of the first datum
print(all_split.get_attr(0))

# print the shape of the first point cloud
print(all_split.get_data(0)['point'].shape)
```

And the output looks ok...

```
INFO - 2021-02-17 09:30:07,475 - customdataset - Found 15 pointclouds for all
{'name': 'train_14', 'path': '/home/equant/work/sandbox/3D/open3dml/lettuce_semantic_segmentation/converted_to_o3d_dataset/val/train_14.npy', 'split': 'all'}
(57617, 3)
```

Finally, if I run the following code, I get errors, which are different depending on if I use `tf` or `torch`...

```
model = ml3d.models.RandLANet()
pipeline = ml3d.pipelines.SemanticSegmentation(model=model, dataset=dataset, max_epoch=100)
pipeline.run_train()
```

The error if I use `tf` is...

```
In [4]:     pipeline.run_train()
   ...: 
INFO - 2021-02-17 09:43:28,433 - semantic_segmentation - <open3d._ml3d.tf.models.randlanet.RandLANet object at 0x7f19932599d0>
INFO - 2021-02-17 09:43:28,433 - semantic_segmentation - Logging in file : ./logs/RandLANet_Custom3D_tf/log_train_2021-02-17_09:43:28.txt
INFO - 2021-02-17 09:43:28,433 - customdataset - Found 12 pointclouds for training
INFO - 2021-02-17 09:43:28,572 - customdataset - Found 1 pointclouds for validation
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-e98bfd14d54b> in <module>
----> 1 pipeline.run_train()

~/.local/lib/python3.8/site-packages/open3d/_ml3d/tf/pipelines/semantic_segmentation.py in run_train(self)
    231 
    232         writer = tf.summary.create_file_writer(self.tensorboard_dir)
--> 233         self.save_config(writer)
    234         log.info("Writing summary in {}.".format(self.tensorboard_dir))
    235         self.optimizer = model.get_optimizer(cfg)

~/.local/lib/python3.8/site-packages/open3d/_ml3d/tf/pipelines/semantic_segmentation.py in save_config(self, writer)
    416         with writer.as_default():
    417             with tf.name_scope("Description"):
--> 418                 tf.summary.text("Open3D-ML", self.cfg_tb['readme'], step=0)
    419                 tf.summary.text("Command line", self.cfg_tb['cmd_line'], step=0)
    420             with tf.name_scope("Configuration"):

AttributeError: 'SemanticSegmentation' object has no attribute 'cfg_tb'
```

And the error if I use `torch` is...
```
In [7]:     pipeline.run_train()
   ...: 
INFO - 2021-02-17 09:45:52,915 - semantic_segmentation - DEVICE : cuda
INFO - 2021-02-17 09:45:52,915 - semantic_segmentation - Logging in file : ./logs/RandLANet_Custom3D_torch/log_train_2021-02-17_09:45:52.txt
INFO - 2021-02-17 09:45:52,915 - customdataset - Found 12 pointclouds for train
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-e98bfd14d54b> in <module>
----> 1 pipeline.run_train()

~/.local/lib/python3.8/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py in run_train(self)
    311 
    312         train_dataset = dataset.get_split('train')
--> 313         train_sampler = train_dataset.sampler
    314         train_split = TorchDataloader(dataset=train_dataset,
    315                                       preprocess=model.preprocess,

AttributeError: 'Custom3DSplit' object has no attribute 'sampler'
```

This error (torch) suggests that there is something wrong with my custom dataset.  I looked in the datasets which are provided (i.e. semantickitti) and don't see any 'sampler' attribute in SemanticKITTISplit(), so I'm not sure how to implement it in my class.

Thanks.

**Comment by sanskar107** [comment] 2021-02-18 14:41
@equant Thanks for pointing this out. There is sampler object missing from the Custom loader. We will fix this as soon as possible.

**Comment by sanskar107** [comment] 2021-02-19 12:07
@equant PR #226 should fix this problem. Feel free to close this issue after testing it.

**Comment by WeikaiTan** [comment] 2021-02-20 00:18
Hello, I also got the problem of AttributeError: 'SemanticSegmentation' object has no attribute 'cfg_tb' using tf.
I don't find the cfg_tb defined in semantic_segmentation.py
`File "/home/weikai/Documents/Code/Open3D-ML-WT/ml3d/tf/pipelines/semantic_segmentation.py", line 233, in run_train
    self.save_config(writer)
  File "/home/weikai/Documents/Code/Open3D-ML-WT/ml3d/tf/pipelines/semantic_segmentation.py", line 418, in save_config
    tf.summary.text("Open3D-ML", self.cfg_tb['readme'], step=0)
AttributeError: 'SemanticSegmentation' object has no attribute 'cfg_tb'`

**Comment by sanskar107** [comment] 2021-02-20 05:59
@WeikaiTan I can reproduce the issue. `cfg_tb` is defined in `scripts/run_pipeline.py`. We will fix this soon. As a work around you can use this script to train your model or define cfg_tb in your training script as defined in `run_pipeline.py`

**Comment by tvkpz** [comment] 2021-03-25 12:37
I get the following error even though the env variable `OPEN3D_ML_ROOT` is set to local codebase head and MyData3D class in defined in my custom data loader mydata3d.py in the datasets folder. 

```
>>> import open3d.ml.torch as ml3d
Using external Open3D-ML in /opt/Open3D-ML
>>> ml3d.datasets
<module 'open3d.ml.torch.datasets' from '/usr/local/lib/python3.6/dist-packages/open3d/ml/torch/datasets.py'>
>>> dataset = ml3d.datasets.MyData3D()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'open3d.ml.torch.datasets' has no attribute 'MyData3D'
```
Any advice what could be going wrong?

**Comment by sanskar107** [comment] 2021-05-03 17:43
@tvkpz you have to add an entry for `MyData3D` in 'ml3d/datasets/__init__.py`, or you can use `ml3d/datasets/customdataset.py` after converting data in required format.

**Comment by sanskar107** [comment] 2021-06-03 08:25
Closing due to inactivity.

**Closed by sanskar107** 2021-06-03 08:25 UTC
