### ISSUE TITLE
ImportError: cannot import name 'iou_bev_cpu' from 'open3d.ml.contrib'

### ISSUE THREAD

**Issue by YoushaaMurhij** [intel-isl/Open3D-ML#201] opened 2020-12-28 18:16 UTC
After using 
`source /path/to/Open3D-ML/set_open3d_ml_root.sh
`
I got this error when trying to test the integration of MyModel

```
 File "tests/test_integration.py", line 13, in test_integration_torch
    import open3d.ml.torch as ml3d
  File "/usr/local/lib/python3.8/dist-packages/open3d/__init__.py", line 111, in <module>
    import open3d.ml
  File "/usr/local/lib/python3.8/dist-packages/open3d/ml/__init__.py", line 35, in <module>
    from . import datasets
  File "/usr/local/lib/python3.8/dist-packages/open3d/ml/datasets.py", line 32, in <module>
    from ml3d.datasets import *
  File "/home/docker_open3d/catkin_ws/src/Open3D_ROS/Open3D-ML/ml3d/datasets/__init__.py", line 5, in <module>
    from .semantickitti import SemanticKITTI
  File "/home/docker_open3d/catkin_ws/src/Open3D_ROS/Open3D-ML/ml3d/datasets/semantickitti.py", line 10, in <module>
    from .utils import DataProcessing
  File "/home/docker_open3d/catkin_ws/src/Open3D_ROS/Open3D-ML/ml3d/datasets/utils/__init__.py", line 1, in <module>
    from .dataprocessing import DataProcessing
  File "/home/docker_open3d/catkin_ws/src/Open3D_ROS/Open3D-ML/ml3d/datasets/utils/dataprocessing.py", line 9, in <module>
    from .operations import *
  File "/home/docker_open3d/catkin_ws/src/Open3D_ROS/Open3D-ML/ml3d/datasets/utils/operations.py", line 5, in <module>
    from ...metrics import iou_bev
  File "/home/docker_open3d/catkin_ws/src/Open3D_ROS/Open3D-ML/ml3d/metrics/__init__.py", line 8, in <module>
    from open3d.ml.contrib import iou_bev_cpu as iou_bev
ImportError: cannot import name 'iou_bev_cpu' from 'open3d.ml.contrib' (/usr/local/lib/python3.8/dist-packages/open3d/ml/contrib/__init__.py)
```

**Comment by ismarintan98** [comment] 2021-01-05 19:07
i have same issue

**Comment by germanros1987** [comment] 2021-02-11 15:31
we are looking into this.

**Comment by sanskar107** [comment] 2021-02-19 08:39
@YoushaaMurhij @ismarintan98 I cannot reproduce this error, Could you let me know the output of following lines of code? I wonder if you have the latest version of Open3D installed.

```
import open3d as o3d
print(dir(o3d.ml.contrib))
```

**Comment by sanskar107** [comment] 2021-06-03 08:26
This is fixed with the latest release.

**Closed by sanskar107** 2021-06-03 08:26 UTC
Labels: bug
